# Generated by Django 4.1.2 on 2023-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='User Name')),
                ('email', models.EmailField(default=None, max_length=50, verbose_name='Email')),
                ('number', models.IntegerField(default='', verbose_name='Contact No')),
                ('gst_number', models.CharField(max_length=50, verbose_name='GST No')),
                ('address', models.TextField(default=None)),
                ('password', models.CharField(default=None, max_length=20, verbose_name='Password')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SellerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='User Name')),
                ('email', models.EmailField(default=None, max_length=50, verbose_name='Email')),
                ('number', models.IntegerField(default='', verbose_name='Contact No')),
                ('Company_name', models.CharField(default='', max_length=20, verbose_name='Company Name')),
                ('address', models.TextField(default=None)),
                ('gst_number', models.CharField(max_length=50, verbose_name='GST No')),
                ('password', models.CharField(default=None, max_length=20, verbose_name='Password')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
