# Generated by Django 4.1.2 on 2023-02-21 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name=' Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('number', models.CharField(default='', max_length=20, verbose_name=' Subject')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerId', models.CharField(max_length=100)),
                ('productImage', models.ImageField(upload_to='product')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.IntegerField(default=0)),
                ('productDescription', models.TextField(default='')),
                ('quantity', models.CharField(max_length=200)),
                ('startdate', models.DateField(default=None)),
                ('enddate', models.DateField(default=None)),
                ('status', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product_category')),
            ],
        ),
    ]
