# Generated by Django 4.1.2 on 2023-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_biddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddetails',
            name='productID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
