# Generated by Django 4.1.2 on 2023-03-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_biddetails_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddetails',
            name='notallotment',
            field=models.BooleanField(default=True),
        ),
    ]
