# Generated by Django 4.1.2 on 2023-03-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_biddetails_notallotment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biddetails',
            old_name='notallotment',
            new_name='action',
        ),
    ]
