# Generated by Django 4.1.2 on 2023-03-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_biddetails_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerregister',
            name='mailsend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerregister',
            name='mailsend',
            field=models.BooleanField(default=False),
        ),
    ]
