# Generated by Django 4.1.2 on 2023-03-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_biddetails_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='pyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('productID', models.CharField(default='', max_length=100)),
                ('SellerId', models.CharField(max_length=100)),
                ('buyerId', models.CharField(max_length=100)),
                ('orderAmount', models.CharField(max_length=50)),
                ('paymentVia', models.CharField(default='', max_length=50)),
                ('paymentMethod', models.CharField(default=None, max_length=50)),
                ('transactionId', models.TextField(default=None)),
            ],
        ),
    ]
